"""empty message

Revision ID: 6458b5c983c7
Revises: 6cc21f5e7c77
Create Date: 2020-03-12 16:17:11.345523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6458b5c983c7'
down_revision = '6cc21f5e7c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_photos', sa.Column('week', sa.Integer(), nullable=True))
    op.drop_column('class_photos', 'img_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_photos', sa.Column('img_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('class_photos', 'week')
    # ### end Alembic commands ###
