"""empty message

Revision ID: 87feb1a6edaa
Revises: 
Create Date: 2020-03-12 15:58:35.973760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87feb1a6edaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('img_filename', sa.String(), nullable=True),
    sa.Column('img_data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('food_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('desc')
    )
    op.create_table('student_photos',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=80), nullable=False),
    sa.Column('student_photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('student_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_photos')
    op.drop_table('food_menu')
    op.drop_table('class_photos')
    # ### end Alembic commands ###
