"""empty message

Revision ID: 9406a1d3965c
Revises: cbf1914682e6
Create Date: 2020-03-13 00:04:39.559807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9406a1d3965c'
down_revision = 'cbf1914682e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_photos', sa.Column('encodings', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_photos', 'encodings')
    # ### end Alembic commands ###
