"""empty message

Revision ID: a90cd30bbc55
Revises: 9406a1d3965c
Create Date: 2020-03-13 01:33:44.988644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90cd30bbc55'
down_revision = '9406a1d3965c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_photos', sa.Column('student_section', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_photos', 'student_section')
    # ### end Alembic commands ###
